Feat/add port
hyperjumptech/branch-preview pull request #6
Opened 2020-12-21 08:37 UTC by sapiderman

# PR request : Add PORT as input

## PR type  

- [x] feature
- [ ] bugfix
- [ ] others:  

### what issue does this pr address

1. if ssh set up is not on default port 22, need a way to set it.
2. add input to specify primary defaults to 'main'  
3. add more docs
4. update README with more info. Add more troubleshooting part

### how did you implement / how did you fix it

1. add PORT as optional input. 
2. Add github main branch as optional input.

### how do you test

1. ran the action 
2. ensure it gets deployed

2020-12-21 15:56 UTC, nicnocquee commented
Changing port doesnt seem to work https://github.com/nicnocquee/test-branch-preview/runs/1589870793?check_suite_focus=true

2020-12-22 08:55 UTC, armedi requested changes
I think we need the following changes to make non default ssh port works.

1. In ssh-keyscan we also need to specify port like so `ssh-keyscan -p $PORT "$HOST" >> ~/.ssh/known_hosts`
2. The command to add git remote also need to be changed like so `git remote add "$APP_NAME" "ssh://dokku@$HOST:$PORT/$APP_NAME"`

2020-12-22 08:55 UTC, armedi commented on entrypoint.sh
> +    ssh "dokku@$HOST -p $PORT dokku apps:create $APP_NAME"
```suggestion
    ssh "dokku@$HOST" -p $PORT dokku apps:create $APP_NAME
```

I test that when the closing quote is placed at the end of the file, the command doesn't work

2020-12-22 08:55 UTC, armedi commented on entrypoint.sh
> +if ! ssh "dokku@$HOST -p $PORT dokku apps:exists $APP_NAME"; then
```suggestion
if ! ssh "dokku@$HOST" -p $PORT dokku apps:exists $APP_NAME; then
```

2020-12-22 12:39 UTC, sapiderman commented on entrypoint.sh
> +    ssh "dokku@$HOST -p $PORT dokku apps:create $APP_NAME"
aah ok.. thanks! last minute moved the quotation mark.. doh! thanks!

2020-12-23 04:09 UTC, armedi commented on README.md
> +A dokku app is created from your branch name so that branch should be deployed to `branch_name.yourdomain.com` when branch_main is not the git primary branch (main/master).
```suggestion
A dokku app is created from your branch name so that branch should be deployed to `branch_name.yourdomain.com` when branch_name is not the git primary branch (main/master).
```

I think it should be `branch_name` because `branch_main` does not refer to anywhere

2020-12-28 06:09 UTC, sapiderman commented on README.md
> +A dokku app is created from your branch name so that branch should be deployed to `branch_name.yourdomain.com` when branch_main is not the git primary branch (main/master).
ya thats a typo

2020-12-31 08:44 UTC, armedi approved these changes

2021-01-01 04:58 UTC, merged